#!/usr/bin/env python

import rospy
from rosgraph_msgs.msg import Log


# printing number on console and log
class TestNode(object):
    def __init__(self):
        """
        publishes log msg through speaking_numberNode topic.
        """
        self.num = 0
        self.name_str = None
        self.rate = rospy.get_param('~speech_rate', 1)
        self.onlyInfo = rospy.get_param('~onlyInfo', False)

    def speaking(self):
        """
        starts to count in an 1 hz rate from 0 upwards and publishes it as SpeakingNumber.
        """
        rate = rospy.Rate(self.rate) # speaking rate
        while not rospy.is_shutdown():
            self.num += 1

            rospy.logdebug(self.get_speech())

            if self.onlyInfo:
                rospy.loginfo(self.get_speech())
            else:
                if (self.num %10) < 5:
                    rospy.loginfo(self.get_speech())
                elif (self.num % 5) < 4:
                    rospy.logwarn(self.get_speech())
                else:
                    rospy.logerr(self.get_speech())
            rate.sleep()

    def get_speech(self):
        return "count: {}".format(self.num)


if __name__ == "__main__":
    rospy.init_node('test_node', anonymous=True)
    my_node = TestNode()
    rospy.sleep(1.0) # initial sleep time
    my_node.speaking()